CarDealershipWeb/Areas/Admin/Controllers/CarController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using CarDealership.Models.ViewModels;
using CarDealership.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarDealershipWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CarController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CarController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Car> carList = _unitOfWork.Car.GetAll(includeProperties:"CarModel").ToList();
            return View(carList);
        }

        public IActionResult Upsert(int? id)
        {
            CarVM carVM = new CarVM()
            {
                Car = new Car(),
                CarModelList = _unitOfWork.CarModel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name + " " + u.Trim,
                    Value = u.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return View(carVM);
            } else
            {
                carVM.Car = _unitOfWork.Car.Get(u => u.Id == id);
                return View(carVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(CarVM carVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                // have to set up this method in case user uploads img..
                string wwwRootPath = _webHostEnvironment.WebRootPath;   // path to wwwroot folder
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string carPath = Path.Combine(wwwRootPath, @"images/car");

                    if (!string.IsNullOrEmpty(carVM.Car.ImageUrl))
                    {
                        // if imageUrl already exists and want to update to new img...
                        var oldImagePath = Path.Combine(wwwRootPath, carVM.Car.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    // otherwise if no prior img exists, just insert new img
                    using (var fileStream = new FileStream(Path.Combine(carPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    // assign the obj's imageUrl..
                    carVM.Car.ImageUrl = @"\images\car\" + fileName;
                }

                // file is null..
                if (carVM.Car.Id == 0)
                {
                    // create
                    _unitOfWork.Car.Add(carVM.Car);
                }
                else
                {
                    _unitOfWork.Car.Update(carVM.Car);
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(carVM);
        }

        public IActionResult Delete(int id)
        {
            if (id < 0)
            {
                return BadRequest();
            }
            CarVM carVM = new()
            {
                Car = _unitOfWork.Car.Get(u => u.Id == id),
                CarModelList = _unitOfWork.CarModel.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name + " " + u.Trim,
                    Value = u.Id.ToString()
                })
            };
            if (carVM.Car == null) { return NotFound(); }
            else { return View(carVM); }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int id)
        {
            if (id < 0)
            {
                return BadRequest();
            }
            CarVM carVM = new()
            {
                Car = _unitOfWork.Car.Get(u => u.Id == id)
                // dont have to set carModelList bc we have it 'ValidateNever'..?
            };
            if (carVM.Car == null) { return NotFound(); }
            else
            {
                // must remove the img too..
                // check if Car obj has an img, then remove img, otherwise skip and jsut remove car...
                if (!string.IsNullOrEmpty(carVM.Car.ImageUrl))
                {
                    var oldImagePath =
                        Path.Combine(_webHostEnvironment.WebRootPath, carVM.Car.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath)) { System.IO.File.Delete(oldImagePath); }
                }

                _unitOfWork.Car.Remove(carVM.Car);
                _unitOfWork.Save();
                TempData["success"] = "Car removed from inventory";
                return RedirectToAction("Index");
            }
        }
    }
}

CarDealershipWeb/Areas/Admin/Controllers/OrderController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using CarDealership.Models.ViewModels;
using CarDealership.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CarDealershipWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller   // order management
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public IActionResult Index()    // displays all the scheduled service appointments..
        {
            //foreach (var claim in ((ClaimsIdentity)User.Identity).Claims)
            //{
            //    Console.WriteLine($"Claim Tpye: {claim.Type}, Value: {claim.Value}");
            //}
            return View();
        }

        public IActionResult Details(int orderId)
        {
            OrderVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(u=>u.Id==orderId, includeProperties:"ApplicationUser"),
                OrderDetail = _unitOfWork.OrderDetail.GetAll(u=>u.OrderHeaderId==orderId, includeProperties:"Service")
            };
            return View(OrderVM);
        }

        #region API CALLS
        // use api calls so we can get json formatted data to use for our dataTables..
        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<OrderHeader> orderHeaders;

            if (User.IsInRole(SD.Role_Admin))
            {
                orderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
            }
            else
            {
                //if 'customer' is logged in, they can view their appointments, but not other peoples
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                orderHeaders = _unitOfWork.OrderHeader.GetAll(u => u.ApplicationUserId == userId, includeProperties: "ApplicationUser");
            }

            return Json(new { data = orderHeaders });
        }

        #endregion
    }
}

CarDealershipWeb/Areas/Customer/Controllers/CartController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using CarDealership.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CarDealershipWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]  // dont have to pass a cartVM to our SummaryPOST b/c the properties from GET will be binded to it..
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId, includeProperties: "Service"),
                OrderHeader = new()
            };

            foreach(var cart in  ShoppingCartVM.ShoppingCartList)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Service.Price;
            }

            return View(ShoppingCartVM);
        }

        public IActionResult Summary()
        {
            // we want the user's name,email,phone to be displayed in the input fields right away..
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId,
                includeProperties: "Service"),
                OrderHeader = new()
            };
            ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
            // populate the values for that user..
            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.Email = ShoppingCartVM.OrderHeader.ApplicationUser.Email;

            // calculate total
            foreach(var cart in ShoppingCartVM.ShoppingCartList)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Service.Price;
            }
             
            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPOST()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM.ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u=>u.AppUserId == userId, 
                includeProperties:"Service");
            ShoppingCartVM.OrderHeader.OrderDate = DateTime.Now;
            ShoppingCartVM.OrderHeader.ApplicationUserId = userId;

            // grab the appUser by doing this..
            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u=>u.Id==userId);

            // calculate total
            foreach (var cart in  ShoppingCartVM.ShoppingCartList)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Service.Price;
            }

            // add our OrderHeader to db..
            _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
            _unitOfWork.Save();

            // create OrderDetail for each service in cart..
            foreach(var cart in ShoppingCartVM.ShoppingCartList)
            {
                OrderDetail orderDetail = new()
                {
                    ServiceId = cart.ServiceId,
                    OrderHeaderId = ShoppingCartVM.OrderHeader.Id,
                    Price = cart.Service.Price
                };
                _unitOfWork.OrderDetail.Add(orderDetail);
                _unitOfWork.Save();
            }

            return RedirectToAction(nameof(ServiceConfirmation), new {id=ShoppingCartVM.OrderHeader.Id});
        }

        // after scheduling service, get sent to confirmation page..
        public IActionResult ServiceConfirmation(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == id, includeProperties:"ApplicationUser");

            // empty the user's shoppingcart after placing order
            List<ShoppingCart> carts = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == orderHeader.ApplicationUserId).ToList();
            _unitOfWork.ShoppingCart.RemoveRange(carts);
            _unitOfWork.Save();
            return View(id);
        }

        public IActionResult Remove(int cartId)
        {
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Service Removed";
            return RedirectToAction(nameof(Index));
        }
    }
}

CarDealershipWeb/Controllers/CarMakeController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealershipWeb.Controllers
{
    public class CarMakeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CarMakeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<CarMake> carMakeList = _unitOfWork.CarMake.GetAll().ToList();
            return View(carMakeList);
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                return View(new CarMake());
            }
            else
            {
                CarMake carMake = _unitOfWork.CarMake.Get(u => u.Id == id);
                return View(carMake);
            }
        }

        [HttpPost]
        public IActionResult Upsert(CarMake carMake)
        {
            if (ModelState.IsValid)
            {
                if (carMake.Id == 0)
                {
                    _unitOfWork.CarMake.Add(carMake);
                    _unitOfWork.Save();
                    TempData["success"] = "Car make added";
                }
                else
                {
                    _unitOfWork.CarMake.Update(carMake);
                    _unitOfWork.Save();
                    TempData["success"] = "Car make updated";
                }
                
                return RedirectToAction("Index");
            }
            else
            {
                // ModelState not valid...
                return View();
            }
        }

        public IActionResult Delete(int id)
        {
            if (id < 0)
            {
                return BadRequest();
            }
            CarMake obj = _unitOfWork.CarMake.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int id)
        {
            if (id < 0)
            {
                return BadRequest();
            }
            CarMake carMake = _unitOfWork.CarMake.Get(u => u.Id == id);
            if (carMake == null) { return NotFound(); }
            _unitOfWork.CarMake.Remove(carMake);
            _unitOfWork.Save();
            TempData["success"] = "Car make removed";
            return RedirectToAction("Index");
        }
    }
}

CarDealershipWeb/Views/Shared/_Layout.cshtml
@using CarDealership.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarDealershipWeb</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarDealershipWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarDealershipWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Orders</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="text-reset nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="CarMake" asp-action="Index">Car Makes</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="CarModel" asp-action="Index">Car Models</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Car" asp-action="Index">Cars</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Service" asp-action="Index">Services</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                Cart <i class="bi bi-cart"></i> &nbsp;
                            </a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CarDealershipWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarDealershipWeb/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

	<script type="text/javascript">
		toastr.success('@TempData["success"]')
	</script>
}

@if (TempData["error"] != null)
{

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

	<script type="text/javascript">
		toastr.error('@TempData["success"]')
	</script>
}