CarDealershipWeb/Areas/Admin/Controllers/ServiceController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using CarDealership.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarDealershipWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ServiceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ServiceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Service> serviceList = _unitOfWork.Service.GetAll().ToList();
            return View(serviceList);
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null)
            {
                return View(new Service());
            }
            else
            {
                Service serviceObj = _unitOfWork.Service.Get(u=>u.Id== id);
                return View(serviceObj);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Service service)
        {
            if (ModelState.IsValid)
            {
                if (service.Id == 0)
                {
                    _unitOfWork.Service.Add(service);
                    TempData["success"] = "Service added";
                } else
                {
                    _unitOfWork.Service.Update(service);
                    TempData["success"] = "Service updated";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(service);
        }

        public IActionResult Delete(int id)
        {
            if (id < 0) { return BadRequest(); }
            Service serviceObj = _unitOfWork.Service.Get(u => u.Id == id);
            if (serviceObj == null) { return NotFound(); }
            return View(serviceObj);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int id)
        {
            if (id < 0) { return BadRequest(); }
            Service serviceObj = _unitOfWork.Service.Get(u => u.Id == id);
            if (serviceObj == null) { return NotFound(); }
            _unitOfWork.Service.Remove(serviceObj);
            _unitOfWork.Save();
            TempData["success"] = "Service removed";
            return RedirectToAction("Index");
        }
    }
}

CarDealershipWeb/Areas/Admin/Views/Service/Delete.cshtml
@model Service

<form method="post">
	<input asp-for="Id" hidden />

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">
				Remove Service
			</h2>
			<hr />
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="@Model.NameOfService" class="p-0"></label>
			<input asp-for="@Model.NameOfService" disabled class="form-control" />
		</div>

		<div class="mb-3 row p-1">
			<label asp-for="@Model.Price" class="p-0"></label>
			<input asp-for="@Model.Price" disabled class="form-control" />

		</div>
		<div class="mb-3 row p-1">
			<label asp-for="@Model.Description" class="p-0"></label>
			<input asp-for="@Model.Description" disabled class="form-control" />
		</div>

		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-danger form-control">Delete</button>

			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Service" asp-action="Index" class="btn btn-secondary border form-control">
					Back To List
				</a>
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CarDealershipWeb/Areas/Admin/Views/Service/Index.cshtml
@model List<Service>

<div container>
	<div class="row pt-4 pb-3">
		<div class="col-6">
			<h2 class="text-primary">
				Services Offered
			</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Service" asp-action="Upsert" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i> Add New Service
			</a>
		</div>
	</div>

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Name of Service</th>
				<th>Price</th>
				<th>Description</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			@foreach (var obj in Model)
			{
				<tr>
					<td>
						@obj.NameOfService
					</td>
					<td>@obj.Price.ToString("c")</td>
					<td>@obj.Description</td>
					<td>
						<div class="w-75 btn-group">
							<a asp-controller="Service" asp-action="Upsert" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
								<i class="bi bi-pencil-square"></i> Edit
							</a>
							<a asp-controller="Service" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
								<i class="bi bi-trash-fill"></i> Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

CarDealershipWeb/Areas/Admin/Views/Service/Upsert.cshtml
@model Service

<form method="post">
	<input asp-for="Id" hidden />

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">
				@(Model.Id != 0 ? "Update" : "Create") Service
			</h2>
			<hr />
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="@Model.NameOfService" class="p-0"></label>
			<input asp-for="@Model.NameOfService" class="form-control" />
			<span asp-validation-for="@Model.NameOfService" class="text-danger"></span>
		</div>

		<div class="mb-3 row p-1">
			<label asp-for="@Model.Price" class="p-0"></label>
			<input asp-for="@Model.Price" class="form-control" />
			<span asp-validation-for="@Model.Price" class="text-danger"></span>
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="@Model.Description" class="p-0"></label>
			<input asp-for="@Model.Description" class="form-control" />
			<span asp-validation-for="@Model.Description" class="text-danger"></span>
		</div>

		<div class="row">
			<div class="col-6 col-md-3">
				@if (Model.Id != 0)
				{
					<button type="submit" class="btn btn-primary form-control">Update</button>
				}
				else
				{
					<button type="submit" class="btn btn-primary form-control">Create</button>
				}
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Service" asp-action="Index" class="btn btn-secondary border form-control">
					Back To List
				</a>
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}