CarDealershipWeb/Areas/Customer/Controllers/CartController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using CarDealership.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CarDealershipWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]  // dont have to pass a cartVM to our SummaryPOST b/c the properties from GET will be binded to it..
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId, includeProperties: "Service"),
                OrderHeader = new()
            };

            foreach(var cart in  ShoppingCartVM.ShoppingCartList)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Service.Price;
            }

            return View(ShoppingCartVM);
        }

        public IActionResult Summary()
        {
            // we want the user's name,email,phone to be displayed in the input fields right away..
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == userId,
                includeProperties: "Service"),
                OrderHeader = new()
            };
            ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
            // populate the values for that user..
            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.Email = ShoppingCartVM.OrderHeader.ApplicationUser.Email;

            // calculate total
            foreach(var cart in ShoppingCartVM.ShoppingCartList)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Service.Price;
            }
             
            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPOST()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM.ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u=>u.AppUserId == userId, 
                includeProperties:"Service");
            ShoppingCartVM.OrderHeader.OrderDate = DateTime.Now;
            ShoppingCartVM.OrderHeader.ApplicationUserId = userId;

            // grab the appUser by doing this..
            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u=>u.Id==userId);

            // calculate total
            foreach (var cart in  ShoppingCartVM.ShoppingCartList)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Service.Price;
            }

            // add our OrderHeader to db..
            _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
            _unitOfWork.Save();

            // create OrderDetail for each service in cart..
            foreach(var cart in ShoppingCartVM.ShoppingCartList)
            {
                OrderDetail orderDetail = new()
                {
                    ServiceId = cart.ServiceId,
                    OrderHeaderId = ShoppingCartVM.OrderHeader.Id,
                    Price = cart.Service.Price
                };
                _unitOfWork.OrderDetail.Add(orderDetail);
                _unitOfWork.Save();
            }

            return RedirectToAction(nameof(ServiceConfirmation), new {id=ShoppingCartVM.OrderHeader.Id});
        }

        // after scheduling service, get sent to confirmation page..
        public IActionResult ServiceConfirmation(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == id, includeProperties:"ApplicationUser");

            // empty the user's shoppingcart after placing order
            List<ShoppingCart> carts = _unitOfWork.ShoppingCart.GetAll(u => u.AppUserId == orderHeader.ApplicationUserId).ToList();
            _unitOfWork.ShoppingCart.RemoveRange(carts);
            _unitOfWork.Save();
            return View(id);
        }

        public IActionResult Remove(int cartId)
        {
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Service Removed";
            return RedirectToAction(nameof(Index));
        }
    }
}

CarDealershipWeb/Areas/Customer/Controllers/ServiceCustomerController.cs
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Security.Claims;

namespace CarDealershipWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ServiceCustomerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ServiceCustomerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Service> serviceList = _unitOfWork.Service.GetAll().ToList();
            return View(serviceList);
        }

        public IActionResult Schedule(int serviceId)
        {
            ShoppingCart cart = new()
            {
                Service = _unitOfWork.Service.Get(u => u.Id == serviceId),
                ServiceId = serviceId
            };
            return View(cart);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Schedule(ShoppingCart cart)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            cart.AppUserId = userId;

            //check if user has a cart for the service already..
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.Get(u=>u.AppUserId == userId &&
            u.ServiceId == cart.ServiceId);

            if (cartFromDb != null)
            {
                // cart exists,
                _unitOfWork.ShoppingCart.Update(cartFromDb);
            } else
            {
                // add cart,
                _unitOfWork.ShoppingCart.Add(cart);
            }
            TempData["success"] = "Cart updated";
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

CarDealershipWeb/Areas/Customer/Views/Cart/Index.cshtml
@model ShoppingCartVM

<form method="post">
	<br />

	<div class="card shadow border-0">
		<div class="card-header bg-secondary bg-gradient text-light m-lg-0 py-4">
			<div class="row px-4">
				<div class="col-6">
					<h5 class="pt-2 text-white">
						Shopping Cart
					</h5>
				</div>
			</div>
		</div>

		<div class="card-body my-4">
			<div class="row"></div>
			<div class="row mb-3 pb-3">
				<div class="col-md-2 offset-md-1">
					<a asp-area="Customer" asp-controller="ServiceCustomer" asp-action="Index" class="btn btn-outline-primary mb-5 btn-sm">Continue Shopping</a>
				</div>
				<div class="col-md-10 offset-md-1">
					@foreach (var item in Model.ShoppingCartList)
					{
						<div class="row border-bottom pb-3">
							<div class="col-12 col-lg-6 pt-md-3">
								<h5 class="text-uppercase text-secondary">@item.Service.NameOfService</h5>
								<p>@Html.Raw(item.Service.Description)</p>
							</div>

							<div class="col-12 col-lg-5 text-center row">
								<div class="col-3 text-md-right pt-2">
									<h6 class="fw-semibold">
										@item.Service.Price.ToString("c")
									</h6>
								</div>

								<div class="col-3 col-sm-4 col-lg-2 pt-2">
									<a asp-action="remove" asp-route-cartId="@item.Id" class="btn btn-danger bg-gradient">
										<i class="bi bi-trash-fill"></i>
									</a>
								</div>
							</div>
						</div>

					}

				</div>
			</div>

			<div class="card-footer bg-white border-0">
				<div class="row">
					<div class="col-md-4 offset-md-4">
						<ul class="list-group md-4">
							<li class="d-flex justify-content-between align-items-center">
								<h5 class="text-dark fw-semibold text-uppercase">Total (USD)</h5>
								<h4 class="text-dark fw-bolder">@Model.OrderHeader.OrderTotal.ToString("c")</h4>
							</li>
						</ul>
					</div>
				</div>

				<div class="row">
					<div class="col-md-2">
						<a asp-action="Summary" class="btn btn-primary border-0 bg-gradient w-100 py-2">Summary</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

CarDealershipWeb/Areas/Customer/Views/Cart/ServiceConfirmation.cshtml
@model int

<div class="container row pt-4">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Order Placed Successfully!</h1>
        Your Order Number is : @Model <br /> <br />
        <img src="~/images/lawn_leaf.jpg" />
    </div>

    <div class="col-12 text-center" style="color:maroon">
        <br />
        Your order has been placed successfully! <br />
    </div>
</div>

CarDealershipWeb/Areas/Customer/Views/Cart/Summary.cshtml
@model ShoppingCartVM

<form method="post">
	<br />
	<div class="container">
		<div class="card shadow border-0">

			<div class="card-header bg-secondary bg-gradient text-light ml-0 py-4">
				<div class="row px-4">
					<div class="col-6">
						<h5 class="pt-2 text-white">
							Order Summary
						</h5>
					</div>
					<div class="col-6 text-end">
						<a asp-action="Index" class="btn btn-outline-danger btn-sm">Back to Cart</a>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="container rounded p-2">
					<div class="row">
						<div class="col-12 col-lg-6 pb-4">
							<div class="row">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Shipping Details:</span>
								</h4>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Name</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.Name" class="form-control" />
									<span asp-validation-for="OrderHeader.Name" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Phone</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.PhoneNumber" class="form-control" />
									<span asp-validation-for="OrderHeader.PhoneNumber" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Email Address</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.Email" class="form-control" />
									<span asp-validation-for="OrderHeader.Email" class="text-danger"></span>
								</div>
							</div>

						</div>
						<div class="col-12 col-lg-5 offset-lg-1">
							<h4 class="d-flex justify-content-between align-items-center mb-3">
								<span class="text-info">Order Summary:</span>
							</h4>
							<ul class="list-group mb-3">
								@foreach(var details in Model.ShoppingCartList)
								{
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@details.Service.NameOfService</h6>
										</div>
										<span class="text-muted">@details.Service.Price.ToString("c")</span>
									</li>
								}

								<li class="list-group-item d-flex justify-content-between bg-light">
									<small class="text-info">Total</small>
									<strong class="text-info">@Model.OrderHeader.OrderTotal.ToString("c")</strong>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col-12 col-md-8 pt-2">
						@* <p style="color:maroon; font-size:14px;">
							Estimate Arrival Date:

						</p> *@
					</div>
					<div class="col-12 col-md-4">
						<button type="submit" value="Place Order" class="btn btn-primary form-control">Place Order</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>