CarDealershipWeb/Areas/Admin/Controllers/CarModelController.cs
//using AspNetCoreGeneratedDocument;
using CarDealership.DataAccess.Repository.IRepository;
using CarDealership.Models;
using CarDealership.Models.ViewModels;
using CarDealership.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarDealershipWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CarModelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CarModelController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<CarModel> carModelList = _unitOfWork.CarModel.GetAll(includeProperties: "CarMake").ToList();
            return View(carModelList);
        }

        public IActionResult Upsert(int? id)
        {
            // use a VM instead so we can include CarMakeList dropdown..
            CarModelVM carModelVM = new()
            {
                CarModel = new CarModel(),
                CarMakeList = _unitOfWork.CarMake.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            if (id == null || id == 0)
            {
                // no id is passed in, create..
                return View(carModelVM);
            } else
            {
                // if id is passed in, update...
                carModelVM.CarModel = _unitOfWork.CarModel.Get(u => u.Id == id);
                return View(carModelVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(CarModelVM carModelVM)
        {
            if (ModelState.IsValid)
            {
                if (carModelVM.CarModel.Id == 0)
                {
                    // create
                    _unitOfWork.CarModel.Add(carModelVM.CarModel);
                    _unitOfWork.Save();
                    TempData["success"] = "New car model added";
                } else
                {
                    // update
                    _unitOfWork.CarModel.Update(carModelVM.CarModel);
                    _unitOfWork.Save();
                    TempData["success"] = "Car model updated";
                }
                return RedirectToAction("Index");
            }

            return View(carModelVM);
        }

        public IActionResult Delete(int id)
        {
            if (id < 0)
            {
                return BadRequest();
            }
            CarModel carModelObj = _unitOfWork.CarModel.Get(u => u.Id == id);
            if (carModelObj == null)
            {
                return NotFound();
            }
            return View(carModelObj);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int id)
        {
            if (id < 0) { return BadRequest(); }
            CarModel carModelObj = _unitOfWork.CarModel.Get(u=>u.Id == id);
            if (carModelObj == null) { return NotFound(); }
            _unitOfWork.CarModel.Remove(carModelObj);
            _unitOfWork.Save();
            TempData["success"] = "Car model removed";
            return RedirectToAction("Index");
        }
    }
}

CarDealershipWeb/Areas/Admin/Views/CarModel/Delete.cshtml
@model CarModel

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Car Model</h2>
			<hr />
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="Name" class="p-0"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>

		<div class="mb-3 row p-1">
			<label asp-for="Trim" class="p-0"></label>
			<input asp-for="Trim" disabled class="form-control" />
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="Engine" class="p-0"></label>
			<input asp-for="Engine" disabled class="form-control" />
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="Description" class="p-0"></label>
			<input asp-for="Description" disabled class="form-control" />
		</div>

		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-danger form-control">Delete</button>
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="CarModel" asp-action="Index" class="btn btn-secondary border form-control">
					Back To List
				</a>
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

CarDealershipWeb/Areas/Admin/Views/CarModel/Index.cshtml
@model List<CarModel>

<div container>
	<div class="row pt-4 pb-3">
		<div class="col-6">
			<h2 class="text-primary">
				Car Models
			</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="CarModel" asp-action="Upsert" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i> Add New Car Model
			</a>
		</div>
	</div>

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Model</th>
				<th>Trim</th>
				<th>Engine</th>
				<th>Make</th>
				<th></th>
			</tr>
		</thead>

		@* <select class="form-select border">
							<option disabled selected>View Trims</option>
							@foreach(var obj in @Model.Where(u=>u.Name==@name))
							{
								<option disabled>@obj.Name @obj.Trim</option>
							}

						</select> *@
		@* <select class="form-select border"
							asp-items="@Model.Where(u=>u.Name==@name).Select(u=> new
							SelectListItem {
							Text=u.Name + " " + u.Trim,
							Value = u.Id.ToString()
							})">
							<option disabled selected>View Trims</option> 
						</select> *@
@* 
		@{
			List<string> carModelNames = new List<string>();
		}
		@foreach(var obj in Model)
		{
			@if (!carModelNames.Contains(obj.Name))
			{
				carModelNames.Add(obj.Name);
			}
		}

		<tbody>
			@foreach (var name in carModelNames.Order())
			{
				<tr>
					<td>@name</td>
					<td>
						<div class="dropdown">
							<button class="form-control border" type="button" data-bs-toggle="dropdown">
								View Trims  <i class="bi bi-caret-down"></i>
							</button>
							<ul class="dropdown-menu">
								@foreach (var obj in @Model.Where(u => u.Name == @name)) {
									<li class="dropdown-item">@obj.Name @obj.Trim</li>
								}
							</ul>
						</div>
						
					</td>
					<td>

					</td>
					<td>

					</td>
					<td class="w-25">
						<div class="w-100 btn-group">
							<div class="dropdown">
								<button class="btn btn-primary form-control border" type="button" data-bs-toggle="dropdown">
									<i class="bi bi-pencil-square"></i> Edit
								</button>
								
								<ul class="dropdown-menu">
									@foreach (var obj in @Model.Where(u => u.Name == @name))
									{
										<a asp-controller="CarModel" asp-action="Upsert" asp-route-id="@obj.Id" class="form-control borrder">
											<li class="dropdown-item">@obj.Name @obj.Trim</li>
										</a>
										
									}
								</ul>
							</div>
							<div class="dropdown">
								<button class="btn btn-danger form-control border" type="button" data-bs-toggle="dropdown">
									<i class="bi bi-trash-fill"></i> Delete
								</button>

								<ul class="dropdown-menu">
									@foreach (var obj in @Model.Where(u => u.Name == @name))
									{
										<a asp-controller="CarModel" asp-action="Delete" asp-route-id="@obj.Id">
											<li class="dropdown-item">@obj.Name @obj.Trim</li>
										</a>
									}
								</ul>
							</div>
							
						</div>
					</td>
				</tr>
			}
		</tbody> *@

		@* CarMakeList = _unitOfWork.CarMake.GetAll().Select(u => new SelectListItem
		{
		Text = u.Name,
		Value = u.Id.ToString()
		}) *@

		@* <div class="mb-3 row p-1">
			<label asp-for="CarModel.CarMakeId" class="p-0"></label>
			<select asp-for="CarModel.CarMakeId" asp-items="@Model.CarMakeList" class="form-select border">
				<option disabled selected>--Select Car Make--</option>
			</select>
			<span asp-validation-for="CarModel.CarMakeId" class="text-danger"></span>
		</div> *@

		<tbody>
			@foreach (var obj in Model.OrderBy(u=>u.Name))
			{
				
				<tr>
					<td>
						@obj.Name
					</td>
					<td>@obj.Trim</td>
					<td>@obj.Engine</td>
					<td>@obj.CarMake.Name</td>
					<td class="w-25">
						<div class="w-100 btn-group">
							<a asp-controller="CarModel" asp-action="Upsert" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
								<i class="bi bi-pencil-square"></i> Edit
							</a>
							<a asp-controller="CarModel" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
								<i class="bi bi-trash-fill"></i> Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

CarDealershipWeb/Areas/Admin/Views/CarModel/Upsert.cshtml
@model CarModelVM

<form method="post">
	<input asp-for="CarModel.Id" hidden />

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">
				@(Model.CarModel.Id != 0 ? "Update" : "Create") Car Model
			</h2>
			<hr />
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="CarModel.Name" class="p-0"></label>
			<input asp-for="CarModel.Name" class="form-control" />
			<span asp-validation-for="CarModel.Name" class="text-danger"></span>
		</div>

		<div class="mb-3 row p-1">
			<label asp-for="CarModel.Trim" class="p-0"></label>
			<input asp-for="CarModel.Trim" class="form-control" />
			<span asp-validation-for="CarModel.Trim" class="text-danger"></span>
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="CarModel.Engine" class="p-0"></label>
			<input asp-for="CarModel.Engine" class="form-control" />
			<span asp-validation-for="CarModel.Engine" class="text-danger"></span>
		</div>
		<div class="mb-3 row p-1">
			<label asp-for="CarModel.Description" class="p-0"></label>
			<textarea asp-for="CarModel.Description" class="form-control"></textarea>
			<span asp-validation-for="CarModel.Description" class="text-danger"></span>
		</div>

		<div class="mb-3 row p-1">
			<label asp-for="CarModel.CarMakeId" class="p-0"></label>
			<select asp-for="CarModel.CarMakeId" asp-items="@Model.CarMakeList" class="form-select border">
				<option disabled selected>--Select Car Make--</option>
			</select>
			<span asp-validation-for="CarModel.CarMakeId" class="text-danger"></span>
		</div>

		<div class="row">
			<div class="col-6 col-md-3">
				@if (Model.CarModel.Id != 0)
				{
					<button type="submit" class="btn btn-primary form-control">Update</button>
				}
				else
				{
					<button type="submit" class="btn btn-primary form-control">Create</button>
				}
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="CarModel" asp-action="Index" class="btn btn-secondary border form-control">
					Back To List
				</a>
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}